### PR TITLE
Add url escaping with jq, support nested notes.

### PR DESCRIPTION
**Pull request by sidequestboy**
Adds dependency of jq for escaping of spaces and special characters in markdown filenames.

Adds support for nested files.

### CODE REVIEW

**Comment by sidequestboy** [comment]
Maybe nested files were working before actually, but spaces in filenames was definitely broken!

I am unsure you want to add jq as a dependency, but it seems like a small dependency anyway.

**Comment by oflisback** [comment]
Thanks a lot for your investigation and PR! This must be fixed and I agree about checking what alternatives there are before adding another dependency. Looking forward to try this out later today.

**Comment by oflisback** [comment]
I pushed an alternative solution to the uri encoding problem: https://github.com/oflisback/obsidian-sync.nvim/commit/6368d1b154a49d9e17bc71cfbc8bf9c2a6b78457 

Do you also think this is a good enough approach?

**Comment by sidequestboy** [comment]
That looks great! I tested and it works for my case, it's nice to not add an external dependency for something so small too

**Pull request closed without merging**
